#!/usr/bin/env bash
# context-lock.sh — Generate and validate context.lock for a repo
#
# Usage (via yourcounterpart):
#   yourcounterpart context sync      → generate context.lock from context/ dir
#   yourcounterpart context validate  → check if context.lock is current
#
# Direct usage:
#   source lib/context-lock.sh
#   context_lock_generate [context_dir] [lock_file]
#   context_lock_validate [context_dir] [lock_file]

# ── Helpers ──────────────────────────────────────────────────────────────────────

_sha256_file() {
  local file="$1"
  if command -v sha256sum &>/dev/null; then
    sha256sum "$file" | awk '{print $1}'
  elif command -v shasum &>/dev/null; then
    shasum -a 256 "$file" | awk '{print $1}'
  else
    echo ""
    echo "ERROR: sha256sum or shasum required" >&2
    return 1
  fi
}

_sha256_string() {
  local str="$1"
  if command -v sha256sum &>/dev/null; then
    echo -n "$str" | sha256sum | awk '{print $1}'
  elif command -v shasum &>/dev/null; then
    echo -n "$str" | shasum -a 256 | awk '{print $1}'
  else
    echo ""
    return 1
  fi
}

# ── Generate ─────────────────────────────────────────────────────────────────────

context_lock_generate() {
  local context_dir="${1:-context}"
  local lock_file="${2:-context.lock}"
  local repo_root="${3:-$PWD}"

  if [[ ! -d "${repo_root}/${context_dir}" ]]; then
    echo "  [!] No '${context_dir}/' directory found in ${repo_root}" >&2
    echo "      Create it first: mkdir -p ${repo_root}/${context_dir}" >&2
    return 1
  fi

  local lines=()
  local all_hashes=""

  while IFS= read -r file; do
    local rel_path
    rel_path="${file#${repo_root}/}"
    local hash
    hash=$(_sha256_file "$file") || return 1
    lines+=("sha256:${hash}  ${rel_path}")
    all_hashes+="${hash}  ${rel_path}\n"
  done < <(find "${repo_root}/${context_dir}" -type f -not -name ".DS_Store" | LC_ALL=C sort)

  if [[ ${#lines[@]} -eq 0 ]]; then
    echo "  [!] No files found in '${context_dir}/' — nothing to hash" >&2
    return 1
  fi

  # Compute aggregate hash of all individual hashes (sorted by path, already done)
  local aggregate
  aggregate=$(_sha256_string "$all_hashes") || return 1

  # Write lock file
  {
    echo "# context.lock — generated by yourcounterpart context sync"
    echo "# DO NOT EDIT MANUALLY. Run: yourcounterpart context sync"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    for line in "${lines[@]}"; do
      echo "$line"
    done
    echo ""
    echo "sha256:${aggregate}  ."
  } > "${repo_root}/${lock_file}"

  echo "  [✓] Generated ${lock_file} (${#lines[@]} files, aggregate: ${aggregate:0:12}...)"
  return 0
}

# ── Validate ─────────────────────────────────────────────────────────────────────

context_lock_validate() {
  local context_dir="${1:-context}"
  local lock_file="${2:-context.lock}"
  local repo_root="${3:-$PWD}"

  if [[ ! -f "${repo_root}/${lock_file}" ]]; then
    echo "  [!] No ${lock_file} found. Run: yourcounterpart context sync" >&2
    return 1
  fi

  local tmp_lock_name=".context.lock.tmp.$$"
  if ! context_lock_generate "$context_dir" "$tmp_lock_name" "$repo_root" &>/dev/null; then
    rm -f "${repo_root}/${tmp_lock_name}"
    return 1
  fi

  local current_hashes expected_hashes
  current_hashes=$(grep "^sha256:" "${repo_root}/${lock_file}" | sort)
  expected_hashes=$(grep "^sha256:" "${repo_root}/${tmp_lock_name}" | sort)
  rm -f "${repo_root}/${tmp_lock_name}"

  if [[ "$current_hashes" == "$expected_hashes" ]]; then
    echo "  [✓] context.lock is current"
    return 0
  else
    echo "  [!] context.lock is stale — context/ files have changed" >&2
    echo "      Run: yourcounterpart context sync" >&2
    return 1
  fi
}

# ── CI check (compare branch vs main) ───────────────────────────────────────────

context_lock_ci_check() {
  local lock_file="${1:-context.lock}"
  local base_branch="${2:-main}"
  local hard_mode="${CONTEXT_LOCK_HARD:-0}"

  # Get lock from main branch
  local main_lock
  main_lock=$(git show "${base_branch}:${lock_file}" 2>/dev/null || echo "")

  if [[ -z "$main_lock" ]]; then
    echo "  [→] No ${lock_file} on ${base_branch} — skipping check"
    return 0
  fi

  if [[ ! -f "$lock_file" ]]; then
    local msg="  [!] ${lock_file} missing on this branch but exists on ${base_branch}"
    if [[ "$hard_mode" == "1" ]]; then
      echo "$msg — BLOCKING (CONTEXT_LOCK_HARD=1)" >&2
      return 1
    else
      echo "$msg — WARNING only (set CONTEXT_LOCK_HARD=1 to block)"
      return 0
    fi
  fi

  local branch_aggregate main_aggregate
  branch_aggregate=$(grep "^sha256:.*  \.$" "$lock_file" | awk '{print $1}')
  main_aggregate=$(echo "$main_lock" | grep "^sha256:.*  \.$" | awk '{print $1}')

  if [[ "$branch_aggregate" == "$main_aggregate" ]]; then
    echo "  [✓] context.lock matches ${base_branch}"
    return 0
  fi

  local msg="  [!] context.lock differs from ${base_branch} — run 'yourcounterpart context sync' and commit the result"
  if [[ "$hard_mode" == "1" ]]; then
    echo "$msg — BLOCKING (CONTEXT_LOCK_HARD=1)" >&2
    return 1
  else
    echo "$msg — WARNING only (set CONTEXT_LOCK_HARD=1 to block)"
    return 0
  fi
}
