#!/usr/bin/env bash
# scripts/context-lock.sh — self-contained context.lock tool
# Copy this file into any repo. No external dependencies.
#
# Usage:
#   bash scripts/context-lock.sh generate
#   bash scripts/context-lock.sh validate
#   bash scripts/context-lock.sh ci-check
#
# Environment:
#   CONTEXT_DIR              context directory       (default: context)
#   CONTEXT_LOCK_FILE        lock file path          (default: context.lock)
#   CONTEXT_LOCK_BASE_BRANCH base branch name        (default: main)
#   CONTEXT_LOCK_HARD        1 = fail on stale lock  (default: 0 for validate, 1 for ci-check)

_ctx_sha256_file() {
  local file="$1"
  if command -v sha256sum &>/dev/null; then
    sha256sum "$file" | awk '{print $1}'
  elif command -v shasum &>/dev/null; then
    shasum -a 256 "$file" | awk '{print $1}'
  else
    echo "ERROR: sha256sum or shasum required" >&2; return 1
  fi
}

_ctx_sha256_string() {
  local str="$1"
  if command -v sha256sum &>/dev/null; then
    echo -n "$str" | sha256sum | awk '{print $1}'
  elif command -v shasum &>/dev/null; then
    echo -n "$str" | shasum -a 256 | awk '{print $1}'
  else
    return 1
  fi
}

context_lock_generate() {
  local context_dir="${1:-${CONTEXT_DIR:-context}}"
  local lock_file="${2:-${CONTEXT_LOCK_FILE:-context.lock}}"
  local repo_root="${3:-$PWD}"

  if [[ ! -d "${repo_root}/${context_dir}" ]]; then
    echo "  [!] No '${context_dir}/' directory found in ${repo_root}" >&2
    return 1
  fi

  local lines=() all_hashes=""
  while IFS= read -r file; do
    local rel_path hash
    rel_path="${file#${repo_root}/}"
    hash=$(_ctx_sha256_file "$file") || return 1
    lines+=("sha256:${hash}  ${rel_path}")
    all_hashes+="${hash}  ${rel_path}\n"
  done < <(find "${repo_root}/${context_dir}" -type f -not -name ".DS_Store" | LC_ALL=C sort)

  if [[ ${#lines[@]} -eq 0 ]]; then
    echo "  [!] No files found in '${context_dir}/' — nothing to hash" >&2
    return 1
  fi

  local aggregate
  aggregate=$(_ctx_sha256_string "$all_hashes") || return 1

  {
    echo "# context.lock — generated by scripts/context-lock.sh generate"
    echo "# DO NOT EDIT MANUALLY. Run: bash scripts/context-lock.sh generate"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    for line in "${lines[@]}"; do echo "$line"; done
    echo ""
    echo "sha256:${aggregate}  ."
  } > "${repo_root}/${lock_file}"

  echo "  [✓] Generated ${lock_file} (${#lines[@]} files, aggregate: ${aggregate:0:12}...)"
}

context_lock_validate() {
  local context_dir="${1:-${CONTEXT_DIR:-context}}"
  local lock_file="${2:-${CONTEXT_LOCK_FILE:-context.lock}}"
  local repo_root="${3:-$PWD}"
  local hard="${CONTEXT_LOCK_HARD:-0}"

  if [[ ! -f "${repo_root}/${lock_file}" ]]; then
    echo "  [!] No ${lock_file} found. Run: bash scripts/context-lock.sh generate" >&2
    return 1
  fi

  local tmp_lock=".context.lock.tmp.$$"
  context_lock_generate "$context_dir" "$tmp_lock" "$repo_root" &>/dev/null || {
    rm -f "${repo_root}/${tmp_lock}"; return 1
  }

  local current expected
  current=$(grep "^sha256:" "${repo_root}/${lock_file}" | LC_ALL=C sort)
  expected=$(grep "^sha256:" "${repo_root}/${tmp_lock}" | LC_ALL=C sort)
  rm -f "${repo_root}/${tmp_lock}"

  if [[ "$current" == "$expected" ]]; then
    echo "  [✓] context.lock is current"
    return 0
  fi

  local msg="  [!] context.lock is stale — run: bash scripts/context-lock.sh generate"
  if [[ "$hard" == "1" ]]; then
    echo "$msg" >&2; return 1
  else
    echo "$msg"; return 0
  fi
}

context_lock_ci_check() {
  local context_dir="${1:-${CONTEXT_DIR:-context}}"
  local lock_file="${2:-${CONTEXT_LOCK_FILE:-context.lock}}"
  local repo_root="${3:-$PWD}"
  local base_branch="${CONTEXT_LOCK_BASE_BRANCH:-main}"
  local hard="${CONTEXT_LOCK_HARD:-1}"
  local failed=0

  _ci_fail() {
    local msg="$1"
    if [[ "$hard" == "1" ]]; then
      echo "  [✗] ${msg}" >&2; failed=1
    else
      echo "  [!] ${msg} (set CONTEXT_LOCK_HARD=1 to block)"
    fi
  }

  echo "  context-lock ci-check (base: ${base_branch})"
  echo ""

  # Check 1 — lock matches current context/ files on this branch
  echo "  [1/2] checking lock is current..."
  if [[ ! -f "${repo_root}/${lock_file}" ]]; then
    _ci_fail "${lock_file} missing — run: bash scripts/context-lock.sh generate"
  else
    local tmp_lock=".context.lock.tmp.$$"
    context_lock_generate "$context_dir" "$tmp_lock" "$repo_root" &>/dev/null || {
      rm -f "${repo_root}/${tmp_lock}"
      _ci_fail "could not regenerate ${lock_file}"
    }
    if [[ -f "${repo_root}/${tmp_lock}" ]]; then
      local current expected
      current=$(grep "^sha256:" "${repo_root}/${lock_file}" | LC_ALL=C sort)
      expected=$(grep "^sha256:" "${repo_root}/${tmp_lock}" | LC_ALL=C sort)
      rm -f "${repo_root}/${tmp_lock}"
      if [[ "$current" != "$expected" ]]; then
        _ci_fail "${lock_file} is stale — context/ changed but lock was not updated. Run: bash scripts/context-lock.sh generate"
      else
        echo "  [✓] lock is current"
      fi
    fi
  fi

  # Check 2 — PR contains all entries from base branch (not behind main)
  echo "  [2/2] checking not behind ${base_branch}..."
  local base_ref
  for ref in "origin/${base_branch}" "${base_branch}"; do
    if git show "${ref}:${lock_file}" &>/dev/null 2>&1; then
      base_ref="$ref"; break
    fi
  done

  if [[ -z "${base_ref:-}" ]]; then
    echo "  [→] no ${lock_file} on ${base_branch} — skipping check 2"
  elif [[ ! -f "${repo_root}/${lock_file}" ]]; then
    _ci_fail "${lock_file} missing on this branch but exists on ${base_branch}"
  else
    local missing=0
    while IFS= read -r entry; do
      [[ -z "$entry" ]] && continue
      if ! grep -qF "$entry" "${repo_root}/${lock_file}"; then
        _ci_fail "missing entry from ${base_branch}: ${entry}"
        _ci_fail "  → a story was added/updated on ${base_branch} after you branched. Rebase and regenerate."
        missing=1
        break
      fi
    done < <(git show "${base_ref}:${lock_file}" 2>/dev/null | grep "^sha256:" | grep -v '[[:space:]]\.$')
    [[ "$missing" -eq 0 ]] && echo "  [✓] not behind ${base_branch}"
  fi

  echo ""
  [[ "$failed" -eq 0 ]] && echo "  [✓] all checks passed" && return 0
  echo "  [✗] checks failed" >&2
  return 1
}

_ctx_usage() {
  echo "Usage: bash scripts/context-lock.sh <generate|validate|ci-check>"
  echo ""
  echo "  generate   regenerate context.lock from context/ directory"
  echo "  validate   check if context.lock matches current context/ files"
  echo "  ci-check   CI enforcement: check 1 (lock current) + check 2 (not behind base branch)"
  echo ""
  echo "Environment:"
  echo "  CONTEXT_DIR              context directory (default: context)"
  echo "  CONTEXT_LOCK_FILE        lock file (default: context.lock)"
  echo "  CONTEXT_LOCK_BASE_BRANCH base branch for ci-check (default: main)"
  echo "  CONTEXT_LOCK_HARD        1=fail on stale, 0=warn only (default: 1 for ci-check)"
}

_ctx_main() {
  local cmd="${1:-}"
  case "$cmd" in
    generate)  context_lock_generate ;;
    validate)  context_lock_validate ;;
    ci-check)  context_lock_ci_check ;;
    *)         _ctx_usage; exit 1 ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  set -euo pipefail
  _ctx_main "$@"
fi
